In [2]:
import numpy as np 
import pandas as pd 
df=pd.read_csv('Employee.csv')
df


Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No   
1     Bachelors         2013       Pune            1   28  Female          No   
2     Bachelors         2014  New Delhi            3   38  Female          No   
3       Masters         2016  Bangalore            3   27    Male          No   
4       Masters         2017       Pune            3   24    Male         Yes   
...         ...          ...        ...          ...  ...     ...         ...   
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 9 columns]

In [3]:
df.head()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [4]:
df.tail()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes   

      ExperienceInCurrentDomain  LeaveOrNot  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0

In [5]:
df.shape

(4653, 9)

In [6]:
df.columns

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='object')

In [7]:
df.isna().sum()

Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

In [8]:
df.dtypes

Education                    object
JoiningYear                   int64
City                         object
PaymentTier                   int64
Age                           int64
Gender                       object
EverBenched                  object
ExperienceInCurrentDomain     int64
LeaveOrNot                    int64
dtype: object

In [9]:

from sklearn.preprocessing import LabelEncoder
lst=['Education','City','Gender','EverBenched']
for i in lst:
    lab=LabelEncoder()
    df[i]=lab.fit_transform(df[i])

    


In [10]:
df.dtypes

Education                    int32
JoiningYear                  int64
City                         int32
PaymentTier                  int64
Age                          int64
Gender                       int32
EverBenched                  int32
ExperienceInCurrentDomain    int64
LeaveOrNot                   int64
dtype: object

In [11]:

x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values


In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train


array([[   0, 2017,    2, ...,    0,    0,    4],
       [   0, 2014,    1, ...,    1,    0,    1],
       [   0, 2015,    2, ...,    0,    1,    3],
       ...,
       [   0, 2016,    0, ...,    0,    0,    1],
       [   0, 2015,    0, ...,    1,    0,    1],
       [   0, 2015,    0, ...,    1,    0,    5]], dtype=int64)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train


array([[-0.51283835,  1.03249079,  1.45984231, ..., -1.22930047,
        -0.32951064,  0.70199459],
       [-0.51283835, -0.57369732,  0.26127755, ...,  0.81347077,
        -0.32951064, -1.21988524],
       [-0.51283835, -0.03830128,  1.45984231, ..., -1.22930047,
         3.03480335,  0.06136798],
       ...,
       [-0.51283835,  0.49709475, -0.93728721, ..., -1.22930047,
        -0.32951064, -1.21988524],
       [-0.51283835, -0.03830128, -0.93728721, ...,  0.81347077,
        -0.32951064, -1.21988524],
       [-0.51283835, -0.03830128, -0.93728721, ...,  0.81347077,
        -0.32951064,  1.3426212 ]])

In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred


array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm


array([[853,  67],
       [195, 281]], dtype=int64)

In [17]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score


0.8123209169054442

In [18]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)


              precision    recall  f1-score   support

           0       0.81      0.93      0.87       920
           1       0.81      0.59      0.68       476

    accuracy                           0.81      1396
   macro avg       0.81      0.76      0.77      1396
weighted avg       0.81      0.81      0.80      1396

